const fs = require('fs');
const path = require('path');

const files = {
  "package.json": `{
  "name": "samastha-graph",
  "private": true,
  "sideEffects": false,
  "type": "module",
  "scripts": {
    "build": "remix vite:build",
    "dev": "remix vite:dev",
    "start": "wrangler pages dev ./build/client",
    "typecheck": "tsc",
    "deploy": "npm run build && wrangler pages deploy ./build/client"
  },
  "dependencies": {
    "@remix-run/cloudflare": "^2.15.0",
    "@remix-run/cloudflare-pages": "^2.15.0",
    "@remix-run/react": "^2.15.0",
    "@sanity/client": "^6.24.1",
    "@sanity/icons": "^3.5.1",
    "@sanity/ui": "^2.11.9",
    "@sanity/vision": "^3.70.0",
    "isbot": "^4.1.0",
    "lucide-react": "^0.470.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sanity": "^3.70.0",
    "styled-components": "^6.1.14"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20241224.0",
    "@remix-run/dev": "^2.15.0",
    "@types/react": "^18.2.20",
    "@types/react-dom": "^18.2.7",
    "autoprefixer": "^10.4.19",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.4",
    "typescript": "^5.1.6",
    "vite": "^5.1.0",
    "vite-tsconfig-paths": "^4.2.1",
    "wrangler": "^3.100.0"
  },
  "engines": {
    "node": ">=20.0.0"
  }
}`,
  "vite.config.ts": `import {
  vitePlugin as remix,
  cloudflareDevProxyVitePlugin as remixCloudflareDevProxy,
} from "@remix-run/dev";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [
    remixCloudflareDevProxy(),
    remix({
      future: {
        v3_fetcherPersist: true,
        v3_relativeSplatPath: true,
        v3_throwAbortReason: true,
      },
    }),
    tsconfigPaths(),
  ],
  ssr: {
    noExternal: ["styled-components", "@emotion/*"],
  }
});`,
  "tsconfig.json": `{
  "include": [
    "**/*.ts",
    "**/*.tsx"
  ],
  "compilerOptions": {
    "lib": ["DOM", "DOM.Iterable", "ES2022"],
    "isolatedModules": true,
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "target": "ES2022",
    "strict": true,
    "allowJs": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./app/*"]
    },
    "noEmit": true
  }
}`,
  "wrangler.toml": `name = "samastha-graph"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"`,
  "functions/[[path]].ts": `import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by remix vite:build
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({ build });`,
  "app/entry.client.tsx": `import { RemixBrowser } from "@remix-run/react";
import { startTransition, StrictMode } from "react";
import { hydrateRoot } from "react-dom/client";

startTransition(() => {
  hydrateRoot(
    document,
    <StrictMode>
      <RemixBrowser />
    </StrictMode>
  );
});`,
  "app/entry.server.tsx": `import type { AppLoadContext, EntryContext } from "@remix-run/cloudflare";
import { RemixServer } from "@remix-run/react";
import { isbot } from "isbot";
import { renderToReadableStream } from "react-dom/server";

export default async function handleRequest(
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  remixContext: EntryContext,
  loadContext: AppLoadContext
) {
  const body = await renderToReadableStream(
    <RemixServer context={remixContext} url={request.url} />,
    {
      signal: request.signal,
      onError(error: unknown) {
        console.error(error);
        responseStatusCode = 500;
      },
    }
  );

  if (isbot(request.headers.get("user-agent") || "")) {
    await body.allReady;
  }

  responseHeaders.set("Content-Type", "text/html");
  return new Response(body, {
    headers: responseHeaders,
    status: responseStatusCode,
  });
}`,
  "tailwind.config.ts": `import type { Config } from 'tailwindcss'

export default {
  content: ['./app/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          dark: '#15664a',
          gold: '#c8a136',
          olive: '#60834f',
          muted: '#7ea99a',
          light: '#eef3f1',
          surface: '#c1d5cd'
        }
      },
      fontFamily: {
        sans: ['"Noto Sans Malayalam"', 'Inter', 'sans-serif'],
        heading: ['"Noto Sans Malayalam"', 'Poppins', 'sans-serif'],
        malayalam: ['"Noto Sans Malayalam"', 'sans-serif'],
      }
    },
  },
  plugins: [],
} satisfies Config`,
  "postcss.config.js": `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`,
  "app/tailwind.css": `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  body {
    @apply bg-brand-light text-gray-800 font-sans antialiased selection:bg-brand-gold selection:text-brand-dark;
  }
}`
};

for (const [filepath, content] of Object.entries(files)) {
  const dirname = path.dirname(filepath);
  if (!fs.existsSync(dirname)) {
    fs.mkdirSync(dirname, { recursive: true });
  }
  fs.writeFileSync(filepath, content);
}

console.log("Scaffolding complete.");
